name: mywallet
description: "A wallet app to track your income and expenses."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.2
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^19.4.1
  fl_chart: ^1.0.0
  http: ^1.5.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
  - family: SFPro
    fonts:
      - asset: lib/assets/fonts/SFPRODISPLAYREGULAR.OTF
        weight: 400
      - asset: lib/assets/fonts/SFPRODISPLAYMEDIUM.OTF
        weight: 500
      - asset: lib/assets/fonts/SFPRODISPLAYBOLD.OTF
        weight: 700

